# Generated by Django 4.1.4 on 2023-08-10 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotels',
            old_name='marked_favortie',
            new_name='marked_favorite',
        ),
    ]
