# Generated by Django 4.1.4 on 2023-08-10 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_rename_marked_favortie_hotels_marked_favorite'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotels',
            new_name='Hotel',
        ),
    ]
