# Generated by Django 4.1.4 on 2023-08-10 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_rename_hotels_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='hotel_name',
        ),
    ]
