# Generated by Django 4.1.4 on 2023-08-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_remove_hotel_hotel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(default='Hotel1', max_length=255),
            preserve_default=False,
        ),
    ]
